### ISSUE TITLE
Help reading .zse files

### ISSUE THREAD

**Issue by tsevast** [cpetrich/zs2decode#9]
Hi @cpetrich 
I would be grateful if you could help me with my problem. I have a file (themis2.zse probably an old version textXpert file) from the Zwick machine which I can't open with textXpert. I try to open it with your script but  I was unable to retrieve the measurements it contains. I am completely inexperienced with programming but I appreciate any help.

Thank you in advance for your time.

Themis

**Comment by cpetrich** [comment]
Hi,
not sure I understand: 
1. Did you get an XML file with the script in the readme (`examples/zs2_to_xml.py`)? 
2. What happens when you run it through `examples/raw_data_dump_from_xml.py`?

If you got a meaningful XML file (check with a text editor) but the extraction script didn't find anything you could browse through the XML file to find really long lines full of numbers (i.e. the data). In the zs2 files those happen to start with `<DataArray type="EE`. If the XML file looks strange then more work may be required. Let me know.

**Comment by tsevast** [comment]
Hi, thank you for the prompt reply.
I hope you forgive my lack of knowledge.
I have a file that I can not open with the program textXpert  (themisbad.zse). I found your script and I thought that I can convert the .zse file to XML to recover the measurement data. Probably .zse is an obsolete type used in the first version of textXpert I have.When I run your script in IDLE :
Traceback (most recent call last):  File "/Users/themistoklissevastiadis/Documents/Themispy.py", line 8, in <module>    data_stream = zs2decode.parser.load(zs2_file_name)  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/zs2decode/parser.py", line 44, in load    data_stream = bytearray( f.read() )  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/gzip.py", line 301, in read    return self._buffer.read(size)  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/_compression.py", line 118, in readall    while data := self.read(sys.maxsize):  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/gzip.py", line 488, in read    if not self._read_gzip_header():  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/gzip.py", line 436, in _read_gzip_header    raise BadGzipFile('Not a gzipped file (%r)' % magic)gzip.BadGzipFile: Not a gzipped file (b'kh')>>> 
I can evaluate none of the above :)  :(
I attach two files themisbad.zse ( I can't open it with textXpert) and themisgood.zse ( I can open it with textXpert).I sent the damaged file to Zwick to recover the data but they didn't solve the problem ( you know how big companies troubleshoot obsolete machines, buy new :) ).I appreciate the time you spent on my problem and looking forward to your reply.
Best regards,Themis

    On Tuesday, June 28, 2022, 12:43:17 AM GMT+3, Chris Petrich ***@***.***> wrote:  
 
 


Hi,
not sure I understand:
   
   - Did you get an XML file with the script in the readme (examples/zs2_to_xml.py)?
   - What happens when you run it through examples/raw_data_dump_from_xml.py?

If you got a meaningful XML file (check with a text editor) but the extraction script didn't find anything you could browse through the XML file to find really long lines full of numbers (i.e. the data). In the zs2 files those happen to start with <DataArray type="EE. If the XML file looks strange then more work may be required. Let me know.

**Comment by cpetrich** [comment]
looks like the attachments were scrubbed. I can look at them if you send links to the files to download.

**Comment by tsevast** [comment]
<link removed>

I thank you in advance
Best regards,Themis    On Wednesday, June 29, 2022, 09:47:50 PM GMT+3, Chris Petrich ***@***.***> wrote:  
 
 


looks like the attachments were scrubbed. I can look at them if you send links to the files to download.

**Comment by cpetrich** [comment]
Well, seems like the format of `.zse` files is rather different from `.zs2` files.

I put the measurements I found in your files here, hope that helps: https://wetransfer.com/downloads/241e65c3a0468198a8f613ddff8bcc7420220629235125/4c8c3b7b4af50315af498e905741ebb020220629235125/b41c50

Looks like each of the files contains over 90 measurement sets.
The `.zse` files can be opened with a text editor, maybe there's useful metadata in plain text.

For future reference, what I did was: split the file at the Latin1 text string `Prüfung Endeÿ` and look for (non-zero) series of data _following_ that. There seem to be 4 non-zero series in each set (plus two that are zero). A data series starts with a 32 bit length indication (number of data values) followed by this number of single precision (i.e. 32 bit) floating point values. I wrote a script that searches for something that looks like a series of measurements and extracts that. Turned out they were all the same length within a set, so I'm assuming all data were found. Between the series in a set are (presumably) metadata that I ignored.

**Comment by tsevast** [comment]
Thank you for your help @cpetrich :) 


Στάλθηκε από το Ταχυδρομείο Yahoo για iPad


Στις Πέμπτη, Ιουνίου 30, 2022, 03:20, ο χρήστης Chris Petrich ***@***.***> έγραψε:




Well, seems like the format of .zse files is rather different from .zs2 files.

I put the measurements I found in your files here, hope that helps: https://wetransfer.com/downloads/241e65c3a0468198a8f613ddff8bcc7420220629235125/4c8c3b7b4af50315af498e905741ebb020220629235125/b41c50

Looks like each of the files contains over 90 measurement sets.
The .zse files can be opened with a text editor, maybe there's useful metadata in plain text.

For future reference, what I did was: split the file at the Latin1 text string Prüfung Endeÿ and look for (non-zero) series of data following that. There seem to be 4 non-zero series in each set (plus two that are zero). A data series starts with a 32 bit length indication (number of data values) followed by this number of single precision (i.e. 32 bit) floating point values. I wrote a script that searches for something that looks like a series of measurements and extracts that. Turned out they were all the same length within a set, so I'm assuming all data were found. Between the series in a set are (presumably) metadata that I ignored.
